# Generated by Django 3.1.4 on 2020-12-21 14:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='cover',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toy',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
