# Generated by Django 3.1.4 on 2020-12-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0002_auto_20201224_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='age',
            field=models.CharField(choices=[('0-2 years', '0-2 years'), ('3-4 years', '3-4 years'), ('5-7 years', '5-7 years'), ('8-11 years', '8-11 years'), ('12-14 years', '12-14 years'), ('14 years+', '14 years+')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='toy',
            name='country',
            field=models.CharField(choices=[('UK', 'UK'), ('US', 'US'), ('Europe', 'Europe'), ('China', 'China'), ('Korea', 'Korea'), ('Japan', 'Japan'), ('SE Asia', 'SE Asia')], default='', max_length=50),
        ),
    ]
