# Generated by Django 3.1.4 on 2020-12-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0003_auto_20201224_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='category',
            field=models.CharField(choices=[('Baby and Toddler toys', 'Baby and Toddler toys'), ('Action figure and Dolls', 'Action figures and Dolls'), ('Stuff toys', 'Stuff toys'), ('Craft and activities', 'Craft and activities'), ('Learning toys', 'Learning toys'), ('Electronics', 'Electronics')], default='', max_length=50),
        ),
    ]
