# Generated by Django 3.1.4 on 2021-04-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0006_auto_20210416_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
