# Generated by Django 3.1.4 on 2020-12-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
