# Generated by Django 3.1.4 on 2020-12-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201225_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='toy_id',
            new_name='toy',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='user_id',
            new_name='user',
        ),
    ]
