# Generated by Django 3.1.4 on 2020-12-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='desc',
            new_name='review',
        ),
    ]
