# Generated by Django 3.1.4 on 2020-12-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='price',
            field=models.FloatField(),
        ),
    ]
